// Real-model parity gate for the native vision encoder.
//
//   vision-encoder METALLIB MODEL_ROOT FIXTURE_DIR
//
// Loads the vision role (packed, or prepared from the model's upstream
// source), encodes the pinned fixture pixels
// (dev/tests/fixtures/vision-parity/MODEL_PROFILE, regenerated by
// `python dev/tools/vision_reference.py PACK OUT_DIR`) through the production
// Metal library, and checks the bf16 embeddings against the fp32 numpy
// reference. It then verifies determinism, a second grid through the same
// scratch arena, and reports the encode time of a 64x64-patch image.

#include "metal/CommandGraph.hpp"
#include "metal/MetalBackend.hpp"
#include "model/ModelFactory.hpp"
#include "ops/Vision.hpp"
#include "tuning/LinearNumerics.hpp"

#import <Foundation/Foundation.h>
#include <CommonCrypto/CommonDigest.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <iostream>
#include <limits>
#include <string>
#include <vector>

namespace {

using splash::metal::BufferStorage;
using splash::metal::CommandGraph;
using splash::metal::MetalBackend;
using splash::metal::MetalBuffer;
using splash::ops::ImageGrid;
using splash::ops::Vision;

std::vector<uint8_t> readFile(const std::string &path) {
  std::ifstream file(path, std::ios::binary);
  if (!file)
    throw std::runtime_error("cannot open " + path);
  return std::vector<uint8_t>(std::istreambuf_iterator<char>(file), {});
}

MetalBuffer upload(MetalBackend &backend, const std::vector<uint8_t> &bytes,
                   const char *label) {
  MetalBuffer buffer =
      backend.allocateBuffer(bytes.size(), BufferStorage::Shared, label);
  std::memcpy(buffer.contents(), bytes.data(), bytes.size());
  return buffer;
}

std::vector<float> encodeOnce(MetalBackend &backend,
                              const Vision &encoder, ImageGrid grid,
                              const MetalBuffer &pixels, uint32_t hiddenSize,
                              double *gpuSeconds) {
  const uint64_t rows = Vision::embeddingRows(grid);
  MetalBuffer embeddings = backend.allocateBuffer(
      rows * hiddenSize * sizeof(uint16_t), BufferStorage::Shared,
      "embeddings");
  std::memset(embeddings.contents(), 0, embeddings.sizeBytes());
  CommandGraph graph;
  encoder.encode(graph, grid, pixels, embeddings);
  const auto timing = backend.submitCommand(graph.dispatches());
  if (gpuSeconds)
    *gpuSeconds = timing.gpuSeconds;
  const auto *words = static_cast<const uint16_t *>(embeddings.contents());
  std::vector<float> result(uint64_t{grid.mergedTokens()} * hiddenSize);
  for (uint64_t index = 0; index < result.size(); ++index)
    result[index] = splash::ops::tuning::bf16ToFloat(words[index]);
  return result;
}

struct Parity {
  double relativeError = 0.0;
  double worstCosine = 1.0;
  double maxAbsolute = 0.0;
};

Parity compare(const std::vector<float> &actual,
               const std::vector<float> &expected, uint32_t hiddenSize) {
  if (!hiddenSize || expected.empty() || expected.size() % hiddenSize ||
      actual.size() != expected.size())
    throw std::runtime_error("embedding size mismatch");
  Parity result;
  double sumAbsError = 0.0, sumAbs = 0.0;
  for (uint64_t row = 0; row < expected.size() / hiddenSize; ++row) {
    double dot = 0.0, normA = 0.0, normB = 0.0;
    for (uint64_t i = 0; i < hiddenSize; ++i) {
      const uint64_t index = row * hiddenSize + i;
      if (!std::isfinite(actual[index]) || !std::isfinite(expected[index]))
        throw std::runtime_error("non-finite parity embedding");
      const double difference = double(actual[index]) - double(expected[index]);
      sumAbsError += std::abs(difference);
      sumAbs += std::abs(double(expected[index]));
      result.maxAbsolute = std::max(result.maxAbsolute, std::abs(difference));
      dot += double(actual[index]) * double(expected[index]);
      normA += double(actual[index]) * double(actual[index]);
      normB += double(expected[index]) * double(expected[index]);
    }
    if (!normA || !normB)
      throw std::runtime_error("zero-norm parity embedding");
    result.worstCosine =
        std::min(result.worstCosine, dot / std::sqrt(normA * normB));
  }
  result.relativeError = sumAbsError / sumAbs;
  return result;
}

void verifyComparison() {
  for (const uint32_t width : {2048U, 5120U}) {
    const std::vector<float> reference(uint64_t{3} * width, 1.0f);
    auto actual = reference;
    std::fill(actual.end() - width, actual.end(), -1.0f);
    if (compare(actual, reference, width).worstCosine > -0.99)
      throw std::runtime_error("parity comparison skipped the final row");
    actual.back() = std::numeric_limits<float>::quiet_NaN();
    try {
      static_cast<void>(compare(actual, reference, width));
    } catch (const std::runtime_error &) {
      continue;
    }
    throw std::runtime_error("parity comparison accepted NaN");
  }
}

std::vector<uint8_t> syntheticPixels(ImageGrid grid) {
  const uint32_t height = grid.height * 16, width = grid.width * 16;
  std::vector<uint8_t> pixels(uint64_t{height} * width * 3);
  for (uint32_t y = 0; y < height; ++y) {
    for (uint32_t x = 0; x < width; ++x) {
      uint8_t *pixel = pixels.data() + (uint64_t{y} * width + x) * 3;
      pixel[0] = static_cast<uint8_t>((x * 7 + y * 3) & 255);
      pixel[1] = static_cast<uint8_t>(((x / 16 + y / 16) & 1) * 255);
      pixel[2] = static_cast<uint8_t>((y * 5) & 255);
    }
  }
  return pixels;
}

bool verifyInjectionWidth(MetalBackend &backend, uint32_t hiddenSize) {
  constexpr uint32_t sourceRows = 4;
  constexpr uint32_t destinationRows = 5;
  const uint64_t sourceElements = uint64_t{sourceRows} * hiddenSize;
  const uint64_t destinationElements = uint64_t{destinationRows} * hiddenSize;
  MetalBuffer source = backend.allocateBuffer(
      sourceElements * sizeof(uint16_t), BufferStorage::Shared,
      "injection source");
  MetalBuffer destination = backend.allocateBuffer(
      destinationElements * sizeof(uint16_t), BufferStorage::Shared,
      "injection destination");
  auto *sourceWords = static_cast<uint16_t *>(source.contents());
  auto *destinationWords = static_cast<uint16_t *>(destination.contents());
  for (uint64_t index = 0; index < sourceElements; ++index)
    sourceWords[index] = static_cast<uint16_t>(index * 17 + 3);
  std::fill_n(destinationWords, destinationElements, uint16_t{0x55aa});

  CommandGraph graph;
  Vision::inject(graph, source, destination, hiddenSize, 1, 2, 2);
  const auto timing = backend.submitCommand(graph.dispatches());
  (void)timing;
  for (uint32_t row = 0; row < destinationRows; ++row) {
    for (uint32_t column = 0; column < hiddenSize; ++column) {
      const uint16_t expected = row >= 2 && row < 4
                                    ? sourceWords[uint64_t{row - 1} * hiddenSize +
                                                  column]
                                    : uint16_t{0x55aa};
      if (destinationWords[uint64_t{row} * hiddenSize + column] != expected)
        return false;
    }
  }
  return true;
}

} // namespace

int main(int argc, char **argv) {
  if (argc != 4) {
    std::cerr << "usage: vision-encoder METALLIB MODEL_ROOT FIXTURE_DIR\n";
    return 2;
  }
  @autoreleasepool {
    try {
      verifyComparison();
      const auto descriptor = splash::model::inspectModelPackage(argv[2]);
      if (descriptor.visionSource == splash::model::VisionSource::None)
        throw std::runtime_error("the model has no vision role");
      MetalBackend backend(argv[1]);
      const auto loader = splash::model::planVisionLoader(backend, argv[2], descriptor);
      const splash::model::QwenVisionWeights model =
          splash::model::loadVisionWeights(backend, argv[2], descriptor, loader.get());
      const std::string fixture = argv[3];

      ImageGrid grid;
      std::ifstream gridFile(fixture + "/grid.txt");
      gridFile >> grid.height >> grid.width;
      if (!grid.valid())
        throw std::runtime_error("fixture grid is invalid");
      const std::vector<uint8_t> pixelBytes = readFile(fixture + "/pixels.bin");
      if (pixelBytes.size() != grid.pixelBytes())
        throw std::runtime_error("fixture pixels do not match the grid");
      const std::vector<uint8_t> expectedBytes =
          readFile(fixture + "/expected_fp32.bin");
      if (expectedBytes.size() != uint64_t{grid.mergedTokens()} *
                                      descriptor.vision.outputHiddenSize *
                                      sizeof(float))
        throw std::runtime_error("fixture projection does not match the model");
      std::vector<float> expected(expectedBytes.size() / sizeof(float));
      std::memcpy(expected.data(), expectedBytes.data(), expectedBytes.size());

      // A scratch arena larger than the fixture exercises padded rows and
      // tokens exactly as serving does for smaller images.
      constexpr uint32_t maximumPatches = splash::ops::kMaximumImagePatches;
      Vision encoder(backend, model.tensors, maximumPatches);
      MetalBuffer pixels = upload(backend, pixelBytes, "fixture pixels");

      double gpuSeconds = 0.0;
      const std::vector<float> first =
          encodeOnce(backend, encoder, grid, pixels,
                     model.tensors.layout.outputHiddenSize, &gpuSeconds);
      unsigned char digest[CC_SHA256_DIGEST_LENGTH];
      CC_SHA256(first.data(), static_cast<CC_LONG>(first.size() * sizeof(float)), digest);
      std::printf("embedding SHA-256: ");
      for (unsigned char byte : digest) std::printf("%02x", byte);
      std::printf("\n");
      const Parity parity =
          compare(first, expected, descriptor.vision.outputHiddenSize);
      std::printf("grid %ux%u: relative_error %.4f max_abs %.4f worst_cosine "
                  "%.4f gpu %.2f ms\n",
                  grid.height, grid.width, parity.relativeError,
                  parity.maxAbsolute, parity.worstCosine, gpuSeconds * 1e3);
      // The bf16 tower drifts ~1-3% relative from fp32 over 27 blocks; that
      // is the correctness bar, and every row must stay tightly aligned.
      bool pass = parity.relativeError < 0.03 && parity.worstCosine > 0.995;

      for (uint32_t width : {2048U, 5120U}) {
        if (!verifyInjectionWidth(backend, width)) {
          std::printf("FAIL: vision injection width %u\n", width);
          pass = false;
        }
      }

      const std::vector<float> second =
          encodeOnce(backend, encoder, grid, pixels,
                     model.tensors.layout.outputHiddenSize, nullptr);
      if (first != second) {
        std::printf("FAIL: encoding is not deterministic\n");
        pass = false;
      }

      // A different grid through the same arena after a larger image: the
      // zeroed key padding and per-grid positions must not leak.
      ImageGrid large{64, 64};
      MetalBuffer largePixels =
          upload(backend, syntheticPixels(large), "large pixels");
      std::vector<double> samples;
      for (int i = 0; i < 5; ++i) {
        double seconds = 0.0;
        std::vector<float> output =
            encodeOnce(backend, encoder, large, largePixels,
                       model.tensors.layout.outputHiddenSize, &seconds);
        samples.push_back(seconds);
        if (!std::all_of(output.begin(), output.end(),
                         [](float value) { return std::isfinite(value); })) {
          std::printf("FAIL: 64x64 encode produced non-finite values\n");
          pass = false;
        }
      }
      std::sort(samples.begin(), samples.end());
      std::printf("grid 64x64 (4096 patches -> 1024 tokens): median gpu %.2f "
                  "ms\n",
                  samples[samples.size() / 2] * 1e3);

      // Exercise the full serving ceiling, then reuse the arena for the
      // small reference fixture to catch stale padding or grid metadata.
      const ImageGrid maximum{128, 128};
      if (maximum.patches() != maximumPatches)
        throw std::logic_error("maximum-grid fixture does not cover serving limit");
      MetalBuffer maximumPixels =
          upload(backend, syntheticPixels(maximum), "maximum pixels");
      const auto maximumFirst = encodeOnce(
          backend, encoder, maximum, maximumPixels,
          model.tensors.layout.outputHiddenSize, nullptr);
      const auto maximumSecond = encodeOnce(
          backend, encoder, maximum, maximumPixels,
          model.tensors.layout.outputHiddenSize, nullptr);
      if (maximumFirst != maximumSecond ||
          !std::all_of(maximumFirst.begin(), maximumFirst.end(),
                       [](float value) { return std::isfinite(value); })) {
        std::printf("FAIL: maximum-grid encode is not finite and deterministic\n");
        pass = false;
      }
      std::printf("maximum grid 128x128 (16384 patches -> 4096 tokens): %s\n",
                  pass ? "passed" : "failed");

      const std::vector<float> third =
          encodeOnce(backend, encoder, grid, pixels,
                     model.tensors.layout.outputHiddenSize, nullptr);
      if (third != first) {
        std::printf("FAIL: fixture encode changed after a larger image\n");
        pass = false;
      }

      ImageGrid small{4, 6};
      MetalBuffer smallPixels =
          upload(backend, syntheticPixels(small), "small pixels");
      const std::vector<float> smallOutput =
          encodeOnce(backend, encoder, small, smallPixels,
                     model.tensors.layout.outputHiddenSize, nullptr);
      if (!std::all_of(smallOutput.begin(), smallOutput.end(),
                       [](float value) { return std::isfinite(value); })) {
        std::printf("FAIL: 4x6 encode produced non-finite values\n");
        pass = false;
      }

      std::printf("vision encoder parity %s\n", pass ? "PASS" : "FAIL");
      return pass ? 0 : 1;
    } catch (const std::exception &error) {
      std::cerr << "FAIL: " << error.what() << '\n';
      return 1;
    }
  }
}
